### PR TITLE
Feat player switch turns

### PR DESCRIPTION
**Pull request by bellvat**
Hi all,

Please review the following:
1. Added game#turn method in the controller, which will switch player turns. This could use some refactoring.
2. Added white_player_user_id to turn_user_id in new.html.erb since the white player will always start the game.
3. Added code to Ajax, saying if the piece drag and drop is successful, call game#turn and switch turn_user_ids

### CODE REVIEW

**Comment by mdunnettstone** [comment]
Looks really good.

Only comment is on chess rules, where the white player always goes first!

Mike

**Comment by mdunnettstone** [comment]
Me again...

Been having a think about the best way to structure this, and I wonder if we're best off having everything in one place. My concern with having one action to update the piece and another for changing the turn_id is that they might get out of sync if one presents an error but the other passes.

My gut feel is that we should have this all happening in the same place so that when a piece move request is sent via the ajax we have, one controller does the following:
- checks if it was this player's go
- checks if the move is valid
- if true, updates the pieces position and changes the turn_id for the game
- if false, renders the correct errors

Something like this:
def update
    @piece = Piece.find(params[:id])
    @game = @piece.game
    # CHECK RIGHT PLAYER'S TURN
    if @game.turn_user_id == current_user.id
      # CHECK VALID MOVE
      @piece.update_attributes(piece_params)
      redirect_to game_path(@game)
      # UPDATE MOVE ID for the game
    else
      # RENDER SOME ERRORS
      redirect_to game_path(@game)
    end
  end

I'll post this in Slack too, because I think this is an important discussion to have!

Mike

**Comment by tscheitle** [comment]
I was also thinking that basically, return true from logic will move a
turn. We could write a function to move the piece, or a function to update
piece with Ajax if the logic returns true.

The logic didn't work to update Ajax with what Mike had written, so I was
waiting to see the turn logic that  Monica comes up witht to see what works
better.

-Tristen

**Comment by bellvat** [comment]
Closing this branch. Updated changes in PR #49.

**Pull request closed without merging**
